services:
  app:
    build: .
    container_name: document-retrieval-api
    ports:
      - "8000:8000"
    environment:
      # 容器内用 Compose 服务名互联，如果elasticsearch和redis有自己的服务名，则需要修改环境变量CACHE_HOST和ES_HOSTS
      CACHE_HOST: redis
      ES_HOSTS: http://elasticsearch:9200
    depends_on:
      - elasticsearch
      - redis

  # 如果已有自己的elasticsearch,可以注释掉下面的elasticsearch服务,修改环境变量ES_HOSTS为你的elasticsearch地址
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.19.15
    container_name: document-retrieval-es
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data

  # 如果已有自己的redis,可以注释掉下面的redis服务,修改环境变量CACHE_HOST为你的redis地址
  redis:
    image: redis:7-alpine
    container_name: document-retrieval-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  es_data:
  redis_data:
